# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Stochastic Search Variable Selection (SSVS) for Logistic Regression
#'
#' Performs SSVS for a logistic regression model with user specified parameters and data
#'
#' @param Y0 vector of responses
#' @param X0 covariate matrix without intercept
#' @param propSD0 vector of standard deviations for normal proposal density
#' @param c0 parameter for spike and slab prior of beta
#' @param tau0 parameter for spike and slab prior of beta
#' @param nMC number of MCMC samples
#' @param nBI number of burn-in samples
#' @param thin number of samples to skip over in thinning
#' @param seed set seed for random number generation
#'
#' @return a nested list of gamma samples, beta samples, and beta acceptance rates
#'
#' @examples
#'
#' ## simulate data;
#'
#' set.seed(1);
#' N  = 8000;
#' p  = 10;
#'
#' X  = matrix(data = rnorm(N*p), nrow=N, ncol=p)
#' beta_true = c(rep(1,p/2),rep(0,p/2))
#' eta = X %*% beta_true
#' pi = exp(eta) / (1 + exp(eta))
#' Y  = rbinom(N,1,pi)
#'
#' ## fit model;
#' test1 <- G3proj::SSVS_Logistic(Y0 = Y, X0 = X, propSD0, c0 = 10,
#'                     tau0 = 0.4, nMC = 1000, nBI = 100, seed=1)
#' @export
SSVS_Logistic <- function(Y0, X0, propSD0, c0, tau0, nMC = 1000L, nBI = 250L, thin = 5L, seed = 1L) {
    .Call(`_G3proj_SSVS_Logistic`, Y0, X0, propSD0, c0, tau0, nMC, nBI, thin, seed)
}

#' MH Normal Proposal Tuning for SSVS under Logistic Regression Model
#'
#' Tunes the normal proposal distribution standard deviation for Metropolis Hastings MCMC for the SSVS variable selection method in a Logistic Regression model.
#'
#' Runs nMc/b number of batches of size b. In each batch the algorithm calculates the Metropolis acceptance rate and adjusts the proposal standard deviation accordingly. As such, nMC must be a multiple of b.
#'
#' @param Y0 vector of responses
#' @param X0 covariate matrix without intercept
#' @param c0 parameter for spike and slab prior of beta
#' @param tau0 parameter for spike and slab prior of beta
#' @param nMC number of MCMC samples
#' @param b batch size
#' @param seed set seed for random number generation
#'
#' @return A nested list of gamma samples, beta samples, beta acceptance rates for each batch, and the proposal standard deviations at the final batch.
#'
#' @examples
#'
#' ## simulate data;
#'
#' set.seed(1);
#' N  = 8000;
#' p  = 10;
#'
#' X  = matrix(data = rnorm(N*p), nrow=N, ncol=p)
#' beta_true = c(rep(1,p/2),rep(0,p/2))
#' eta = X %*% beta_true
#' pi = exp(eta) / (1 + exp(eta))
#' Y  = rbinom(N,1,pi)
#'
#' ## fit model;
#' test1 <- G3proj::SSVS_Tuning(Y0 = Y, X0 = X, c0 = 10,
#'                     tau0 = 0.4, nMC = 1000, b = 50)
#' @export
SSVS_Tuning <- function(Y0, X0, c0, tau0, nMC = 1000L, b = 50L, seed = 1L) {
    .Call(`_G3proj_SSVS_Tuning`, Y0, X0, c0, tau0, nMC, b, seed)
}

