# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BLRM_Tuning <- function(Y0, X0, PriorVar, nMC = 10000L, b = 50L, seed = 1L) {
    .Call('_G3proj_BLRM_Tuning', PACKAGE = 'G3proj', Y0, X0, PriorVar, nMC, b, seed)
}

BLRM_fit_mwg <- function(Y0, X0, PriorVar, propSD0, nMC = 1000L, nBI = 250L, thin = 5L, seed = 1L) {
    .Call('_G3proj_BLRM_fit_mwg', PACKAGE = 'G3proj', Y0, X0, PriorVar, propSD0, nMC, nBI, thin, seed)
}

SSVS_Logistic <- function(Y0, X0, propSD0, c0, tau0, nMC = 1000L, nBI = 250L, thin = 5L, seed = 1L) {
    .Call('_G3proj_SSVS_Logistic', PACKAGE = 'G3proj', Y0, X0, propSD0, c0, tau0, nMC, nBI, thin, seed)
}

SSVS_Tuning <- function(Y0, X0, c0, tau0, nMC = 1000L, b = 50L, seed = 1L) {
    .Call('_G3proj_SSVS_Tuning', PACKAGE = 'G3proj', Y0, X0, c0, tau0, nMC, b, seed)
}

